import './assets/scripts/master';
import './assets/styles/BackgroundColors.scss';
import './assets/styles/CartSidebar.scss';
import './assets/styles/Index.scss';
import './assets/styles/Master.scss';
import './assets/styles/Inputs.scss'
import './assets/styles/TextShades.scss';
import './assets/styles/Typography.scss';
import './assets/styles/Wrappers.scss';